# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    -  run: echo "Thank you ${{ github.actor }} for submitting your assignment\n"
    -  run: echo "Your assignment is being checked"
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies
      run: npm install
      
    - name: Compile the contract
      run: npx hardhat compile
      
    - name: Run the tests
      run: | 
        npx hardhat test # Check if tests passed
        if [ $? -ne 0 ]; 
          then echo "Tests failed" exit 1
          else echo "All tests passed" 
        fi
